### PR TITLE
Optimised images

### PR DESCRIPTION
**Pull request by gingerbeardman**
loose files
> Saved 5 MB out of 19.8 MB. 25% overall (up to 97.3% per file)
screen shot 2019-02-27 at 10 35 11

data.zip
> Saved 10.9 MB out of 42.6 MB. 25.7% overall (up to 97.3% per file)
screen shot 2019-02-27 at 12 36 25

### CODE REVIEW

**Comment by rsn8887** [comment]
Thank you!

It looks good. Does this have any effect on the image quality?

**Comment by gingerbeardman** [comment]
This type of optimisation does not affect image quality.

It basically just brute forces all PNG compression schemes and keeps the one that is smallest file size. In some cases it will also reduce colour depth from 16-bit to 8-bit if the image does not need/use that depth.

**Comment by rsn8887** [comment]
Perfect! Thanks!

**Comment by gingerbeardman** [comment]
The optimisation I am trying next is slightly lossy, we'll see what the results are.

**Comment by gingerbeardman** [comment]
So @rsn8887 it looks like another 25% (quick test over ~200 files) can be saved by doing slightly lossy optimisation. But it would take a long time for my slow computer to do this for all files.

Example:

lossless (8680 bytes)
sasquatch12_1_038-160x104

lossy (5,171 bytes)
sasquatch12_1_038-160x104

**Comment by rsn8887** [comment]
I‘d rather not do lossy compression. It will degrade the graphics, even in game, it at least in the menus. I agree it looks ok, but still I’d rather have pixel perfect versions of all the graphics just like they are in the official distribution for Windows etc.

Did you play with the new data from data.zip from this PR? It would be good to test that the game loads the new gfx just fine. It would be good to double check.

I might update the release files and try to get the update into the homebrew store, so future users can enjoy faster downloads.

Another thing to try would be zipped level directories. That would make unpacking much faster. The idea is to zip level directories like enigmai->enigmai.zip and see if the game can load from the zip files just fine.

I suspect there’s a problem with the zip code because it was never used in the Windows and MacOS versions. But I never tested it. An easy test would be to rename enigma folder and put the zipped version. Then when there’s a problem with zip, it can be renamed back without having to copy over the 10000 files again.

**Comment by gingerbeardman** [comment]
I'll take some screen grabs of the game running with the optimised images.

And I won't pursue slightly-lossy optimisation, as I agree with your concerns.

**Pull request merged**
